name: Upgrade Elementor test

on:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Elementor version from Wordpress svn'
        required: false
        default: ''

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-plugin:
    name: Build plugin
    runs-on: ubuntu-latest
    if: startsWith( github.repository, 'elementor/' )
    outputs:
      changelog_diff: ${{ steps.changelog_diff_files.outputs.diff }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Restore NPM Cache
        uses: actions/cache/restore@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npx grunt build
      - name: Cache node modules
        uses: actions/cache/save@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Save build to cache
        uses: actions/cache/save@v3
        with:
          path: ./build/*
          key: playwright-build-${{ github.sha }}

  run-upgrade-test:
    name: Playwright plugin upgrade test
    runs-on: ubuntu-latest
    needs: [build-plugin]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Restore NPM from cache
        uses: actions/cache/restore@v3
        id: restore-npm
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Restore build from cache
        uses: actions/cache/restore@v3
        id: restore-build
        with:
          path: ./build/*
          key: playwright-build-${{ github.sha }}
      - name: Install dependencies
        run: |
            npm ci
            cd ./tests/playwright/upgrade-test && npm ci
      - name: Run upgrade test
        run:  cd ./tests/playwright/upgrade-test && npm run test:upgrade:elementor
        env:
          ELEMENTOR_PLUGIN_VERSION: ${{inputs.version}}
      - name: Setup playwright tests
        run: cd ./tests/playwright/upgrade-test && npm run test:setup
      - name: Install chromium
        run: npx playwright install chromium
      - name: Run Playwright tests
        run: npm run test:playwright:elements-regression -- --grep="Test heading template"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-test-results-elements-regression
          path: test-results/
          retention-days: 3

  test-result:
    needs: run-upgrade-test
    if: ${{ always() }} # Will be run even if 'Playwright' matrix will be skipped
    runs-on: ubuntu-22.04
    name: Playwright - Test Results
    steps:
      - name: Test status
        run: echo "Test status is - ${{ needs.run-upgrade-test.result }}"
      - name: Check Playwright matrix status
        if: ${{ needs.run-upgrade-test.result != 'success' && needs.run-upgrade-test.result != 'skipped' }}
        run: exit 1


